apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - dockerhubregcred.yaml
  - secret-mysql-clientes.yaml
  - secret-mysql-api.yaml
  - secret-mysql-abdv2.yaml
  - nfs-pv.yaml
  - nfs-pvc.yaml
  - configmap.yaml
  - deployment.yaml
  - service.yaml
images:
  - name: afloresmansilla/backend-clientes-mklens
    newTag: latest
