apiVersion: v1
kind: Secret
metadata:
  name: mysql-clientes
  labels:
    app: backend-clientes-mklens
type: Opaque
stringData:
  host: "10.15.27.60"
  port: "3306"
  username: "mklens"
  password: "&QaBM9%XFgLm!nny"
  database: "marketlens_clientes"
