apiVersion: v1
kind: Secret
metadata:
  name: mysql-api
  labels:
    app: backend-clientes-mklens
type: Opaque
stringData:
  host: "10.15.27.60"
  port: "3306"
  username: "pBwdEJ36XiMP"
  password: "LNvBUDmg4rCmgVF0kym"
  database: "apiv2"
